In [1]:
inputs = [1 , 2 , 3, 2.5]

In [2]:
weights = [[0.2, 0.8 , -0.5, 1.0],
           [0.5, -0.91 , 0.26, -0.5],
           [-0.26, -0.27 , 0.17 , 0.87]]

In [3]:
biases = [2, 3 , 0.5]

In [4]:
# Python code
layer_outputs = []
for neuron_weights , neuron_biases in zip(weights, biases):
    neuron_output = 0
    for n_input , weight in zip(inputs , neuron_weights):
        neuron_output += n_input * weight
    neuron_output += neuron_biases
    layer_outputs.append(neuron_output)
print(layer_outputs)

[4.8, 1.21, 2.385]


In [5]:
import numpy as np

In [6]:
outputs = np.dot(weights , inputs) + biases
print(outputs)

[4.8   1.21  2.385]


In [7]:
outputs.shape

(3,)

np.dot(inputs , weights ) doesn't work because the shape of the inputs matrix is 4x1 and size of the weights matrix is 3x4

Matrix multiplication is not possible . 

Hence only np.dot(weights,  inputs) works and it returns the size of 3x1 

# BATCHES


In [8]:
inputs = [[1, 2 , 3 , 2.5],
          [2.0, 5.0 , -1.0 , 2.0],
          [-1.5 , 2.7 , 3.3 , -0.8]]
weights = [[0.2, 0.8 , -0.5, 1.0],
           [0.5, -0.91 , 0.26, -0.5],
           [-0.26, -0.27 , 0.17 , 0.87]]
biases = [2, 3 , 0.5]


Here , inputs is in 3x4 shape and weights is also in 3x4 shape . Matrix multiplication is not possible if we multiple with inputs x weights or weights x inputs . 
Therefore we transpose the weights so that the shape becomes 4x3 . Now we can do a dot product and the output will be 3x3 or 4x4 . 

And again here we need to multiply inputs x weights because the output of weights(T) x inputs is going to be of shape 4x4 . But the bias is of shape 3x1 and the matrix addition would not be possible . 

In [9]:
layer1_outputs = np.dot(inputs , np.array(weights).T) + biases
layer1_outputs

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

Adding a Layer to neural network

In [10]:
weights2 = [[0.1 , -0.14 , 0.5],
            [-0.5, 0.12 , -0.33],
            [-0.44, -0.73 , -0.13]]
biases2 =  [-1 , 2 , -0.5]

In [11]:
layer1_outputs = np.dot(inputs , np.array(weights).T) + biases
layer1_outputs

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [12]:
layer2_outputs = np.dot(layer1_outputs , np.array(weights2).T) + biases2
layer2_outputs

array([[ 0.5031 , -1.04185, -3.80535],
       [ 0.2434 , -2.7332 , -3.1207 ],
       [-0.99314,  1.41254, -1.89101]])

Simplifying

Adding Object Layers

In [13]:
X = [[1, 2 , 3 , 2.5],
          [2.0, 5.0 , -1.0 , 2.0],
          [-1.5 , 2.7 , 3.3 , -0.8]]

In [37]:
print(0.10*np.random.rand(4,3))

# These are the weights of the 3 neurons
# [[9.13541965e-01 4.58068068e-01 6.73847001e-01]
#  [8.31681615e-01 6.92418838e-01 4.10968595e-01]
#  [2.29277594e-01 6.80043915e-01 8.91694855e-01]
#  [2.34997555e-04 2.10783015e-01 4.05103993e-01]]

# This is the example output . The values are more than 1 . These are the weights so using high values is not ideal.
# That is the reason 0.10 is multiplied.

# THe reason we are initialising the matrix as 3x4 is to avoid Transpose in the later operations . 



[[0.05680446 0.09255966 0.00710361]
 [0.00871293 0.00202184 0.08326198]
 [0.07781568 0.08700121 0.09786183]
 [0.07991586 0.04614794 0.07805292]]


In [35]:
np.random.seed(0)

In [44]:
class Layer_Dense:
    def __init__(self , n_inputs , n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs , n_neurons)
        self.biases = np.zeros((1,n_neurons))
    def forward(self , inputs):
        self.output = np.dot(inputs , self.weights) + self.biases

In [45]:
layer1 = Layer_Dense(4, 5)
layer2 = Layer_Dense(5, 2)

In [46]:
layer1.forward(X)
print(layer1.output)

[[-0.41547002  0.70869409  0.31835306  0.69519709  0.51953139]
 [-0.52802928  0.72118727  0.89654695  0.64941058  0.33951667]
 [-0.7995324   0.71286305  0.49708831  0.58571338 -0.19256797]]


In [47]:
layer2.forward(layer1.output)
print(layer2.output)

[[-0.01530532  0.01493205]
 [-0.07502277  0.06932956]
 [ 0.00019507  0.04820454]]


ReLU

In [48]:
inputs = [0 , 2 , -1 , 3.3 , -2.7 , 1.1 , 2.2 , -100]


In [51]:
output = []
for i in inputs:
    if i > 0:
        output.append(i)
    elif i <= 0:
        output.append(0)
print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [52]:
output = []
for i in inputs:
    output.append(max(0,i))
print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [55]:
#importing dataset
from nnfs.datasets import spiral_data

X , y = spiral_data(100 , 3)

In [56]:
class Layer_Dense:
    def __init__(self , n_inputs , n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs , n_neurons)
        self.biases = np.zeros((1,n_neurons))
    def forward(self , inputs):
        self.output = np.dot(inputs , self.weights) + self.biases

class Activation_ReLU:
    def forward(self,  inputs):
        self.output = np.maximum(0 , inputs)


In [62]:
layer1 = Layer_Dense(2, 5)
activation1 = Activation_ReLU()

In [63]:
layer1.forward(X)
print(layer1.output)
activation1.forward(layer1.output)
print(activation1.output)

[[ 0.          0.          0.          0.          0.        ]
 [ 0.00073365  0.00064859 -0.00037511 -0.00056511 -0.00071413]
 [ 0.00163209  0.000889   -0.00082208 -0.00173472 -0.00097863]
 ...
 [-0.07529232  0.00357203  0.03692608  0.11846862 -0.00395959]
 [-0.06241302  0.0316388   0.02996742  0.12293083 -0.03486913]
 [-0.07513902  0.00835974  0.03674352  0.12236185 -0.00923292]]
[[0.         0.         0.         0.         0.        ]
 [0.00073365 0.00064859 0.         0.         0.        ]
 [0.00163209 0.000889   0.         0.         0.        ]
 ...
 [0.         0.00357203 0.03692608 0.11846862 0.        ]
 [0.         0.0316388  0.02996742 0.12293083 0.        ]
 [0.         0.00835974 0.03674352 0.12236185 0.        ]]
