In [5]:
import numpy as np
from nnfs.datasets import spiral_data

In [6]:
np.random.seed(0)

In [7]:
class Layer_Dense:
    def __init__(self , n_inputs , n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs , n_neurons) #Randomly assigned weights
        self.biases = np.zeros((1,n_neurons)) # 0 Bias
    def forward(self , inputs):
        self.output = np.dot(inputs , self.weights) + self.biases

In [8]:
class Activation_ReLU:
    def forward(self,  inputs):
        self.output = np.maximum(0 , inputs)


In [9]:
class Activation_Softmax:
    def forward(self , inputs):
        exp_values = np.exp(inputs - np.max(inputs , axis = 1 , keepdims= True))
        probabilities =  exp_values / np.sum(exp_values , axis = 1 , keepdims= True)
        self.output = probabilities
        

In [15]:
class Loss:
    def calculate(self , output , y):
        sample_losses = self.forward(output, y)
        data_loss = np.mean(sample_losses)
        return data_loss

In [16]:
class Loss_CategoricalCrossEntropy(Loss):
    def forward(self , y_pred , y_true):
        samples = len(y_pred)
        y_pred_clipped = np.clip(y_pred , 1e-7 , 1 - 1e-7)

        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[range(samples) , y_true]
        elif len(y_true.shape == 2):
            correct_confidences = np.sum(y_pred_clipped * y_true , axis = 1)

        negative_log_likelihoods = -np.log(correct_confidences)
        return negative_log_likelihoods


In [10]:
X , y = spiral_data(samples= 100 , classes= 3 )

In [11]:
dense1 = Layer_Dense(2 , 3)
activation1 = Activation_ReLU()

dense2 = Layer_Dense(3 , 3)
activation2 = Activation_Softmax()

In [12]:
dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

In [14]:
print(activation2.output[:5])

[[0.33333333 0.33333333 0.33333333]
 [0.33331734 0.33331832 0.33336434]
 [0.3332888  0.33329153 0.33341967]
 [0.33325941 0.33326395 0.33347665]
 [0.33323311 0.33323926 0.33352763]]


In [17]:
loss_function = Loss_CategoricalCrossEntropy()
loss = loss_function.calculate(activation2.output , y)

print("Loss: " ,loss)

Loss:  1.0984449588022467
